name: Catalogue CICD 
run-name: Catalogue CICD 
on:
  push:
    branches:
    - main
jobs:
  ci:
    uses: azawsdevops/github-reusable-modules/.github/workflows/ci.yaml@main
    with:
      component: cart
  deploy:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: Catalogue
      appType: nodejs